name: Scrape Connections

on:
  schedule:
    # 1st of every month at 9 AM IST (3:30 UTC)
    - cron: '30 3 1 * *'
  workflow_dispatch: {}

concurrency:
  group: ci
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  scrape-connections:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Show Chrome version
        run: chrome --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env with DECRYPT_KEY only
        shell: bash
        run: |
          set -e
          : > .env
          if [ -n "${{ secrets.DECRYPT_KEY }}" ]; then
            echo "DECRYPT_KEY=${{ secrets.DECRYPT_KEY }}" >> .env
          fi

      - name: Run scrape_connections.py (headless)
        env:
          HEADLESS: '1'
        run: |
          python scrape_connections.py

      - name: Commit and push changes (end only)
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore: update scraped connections data [skip ci]"
            if git pull --rebase --no-edit; then
              git push
            else
              git rebase --abort
              echo "Rebase failed due to conflicts, skipping push"
            fi
          else
            echo "No changes to commit."
          fi